### PR TITLE
Add validation that log in input values are not null, include extra error massages to be displayed to the user.

### LINKED ISSUE #80: Display corresponding error to user if login email or password values are less than expected.
The minimum length for the email field is 5 characters, while for the password field it is 8 characters. When validation fails for either field, the corresponding error should be displayed to indicate the incorrect field value.

### PR DESCRIPTION
**Pull request by UserOlena**
requires testing. In order to perform testing need to pull previous commit tat is not merged yet.

closes #80

### CODE REVIEW

**Comment by UserOlena** [comment]
> requires testing. In order to perform testing need to pull previous commit tat is not merged yet.

Merge conflict has been successfully resolved, and the issues that were not functioning as expected have been fixed. Extensive testing has been conducted on the sign-up, log out, and log in functionality, and at the time of creating this pull request, no errors were encountered in these routes. If length of the email or password input field values is less than expected (email - 5, password - 8), then corresponding error will be displayed to the user.

During the review, please ensure that the functionality you were working on in the sign-in handler and route is thoroughly reviewed to confirm its proper functioning as well.

**Comment by UserOlena** [comment]
Formatted userRoutes, user-auth and sever.js (by clicking on Format Document option) as after the merge conflict almost all the lines were shifted to the left

**Comment by JDempe** [comment]
Only thing I notice is that in standard flow of signing up for an account, I type my PW in and then try to click create, but nothign happens.  I then have to click somewhere on the modal to get the error to pop up.  Is it possible to get the error to pop up within the create account button event listener?

**Comment by JDempe** [comment]
And last comment is the alert area seems to be underneath all the textboxes except the bottom one, it covers half the text.  Can it be shifted?

**Comment by JDempe** [comment]
> Only thing I notice is that in standard flow of signing up for an account, I type my PW in and then try to click create, but nothign happens. I then have to click somewhere on the modal to get the error to pop up (i think you said error checking happens on unfocus of the textbox?). Is it possible to get the error to pop up within the create account button event listener?

Well it seems like this is more or less resolved by the disable of create  button, the other branch @UserOlena

**Review by JDempe — DISMISSED** [review]

**Review by JDempe — APPROVED** [review]

**Pull request merged**
