### PR TITLE
Feature/add pinning feature

### PR DESCRIPTION
**Pull request by JDempe**
On the discover page, if the pin is in your saved pins list, the pin is black.  If not, it is transparent.  If you are not logged in, clicking the pin button brings up a popover telling you to login

### CODE REVIEW

**Review by Bandhavib — DISMISSED** [review]

**Review by UserOlena — CHANGES_REQUESTED** [review]
After pinning multiple posts and updating the page, only 3 out of all saved pins are shown as pinned.

**Comment by JDempe** [comment]
Good catch!  Made the column take longer strings

**Comment by UserOlena** [comment]
Issue with pinning more than 3 pins is resolved!

**Review by UserOlena — APPROVED** [review]
All pinned posts were still pinned after page reloading. Same with unpinned post. After page reloading they were unpinned correctly. Pin icon works as expected. If user is not logged in and clicks to pin a post, the pop up warning is displayed. If unpinned - icon is transparent. If pinned - dark greyed and angled.

**Pull request merged**
